/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao.TPrincipalAluno;

import Visao.TDatabase.DAO;
import Visao.TModels.Aluno;
import Visao.TModels.Materia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cleis
 */
public class TelaCursos_Materias extends javax.swing.JFrame {

    private Aluno aluno;

    public TelaCursos_Materias(Aluno aluno) {
        this.aluno = aluno;
        initComponents();
        carregarMaterias();
    }

    public TelaCursos_Materias() {
        initComponents();
    }

    private void carregarMaterias() {
        DAO DAO = new DAO();
        ArrayList<Materia> materias = DAO.getMateriasByAlunoId(aluno.getId());

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Materia materia : materias) {
            model.addElement(materia.getNome());
        }
        comboboxMaterias.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAulas = new javax.swing.JTextPane();
        comboboxMaterias = new javax.swing.JComboBox<>();
        btnConsultarMaterias = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnConsultarLivros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(txtAulas);

        comboboxMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxMateriasActionPerformed(evt);
            }
        });

        btnConsultarMaterias.setText("Consultar Aulas");
        btnConsultarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMateriasActionPerformed(evt);
            }
        });

        jCalendar1.setBackground(new java.awt.Color(255, 255, 255));

        btnConsultarLivros.setText("Consultar Livros");
        btnConsultarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarLivrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsultarLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboboxMaterias, javax.swing.GroupLayout.Alignment.TRAILING, 0, 316, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(3, 3, 3)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnConsultarLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(658, 259));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMateriasActionPerformed
        DAO alunoDAO = new DAO();
        String nomeMateria = (String) comboboxMaterias.getSelectedItem();
        Materia materia = alunoDAO.getMateriaByNome(nomeMateria);
        ArrayList<String> aulas = alunoDAO.getAulasByMateriaId(materia.getId());

        StringBuilder aulasText = new StringBuilder();
        for (String aula : aulas) {
            aulasText.append(aula).append("\n");
        }
        txtAulas.setText(aulasText.toString());    }//GEN-LAST:event_btnConsultarMateriasActionPerformed

    private void comboboxMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxMateriasActionPerformed

    private void btnConsultarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLivrosActionPerformed
        String nomeMateria = (String) comboboxMaterias.getSelectedItem();
        if (nomeMateria != null) {
            DAO alunoDAO = new DAO();
            Materia materia = alunoDAO.getMateriaByNome(nomeMateria);
            if (materia != null) {
                TelaLivros telaLivros = new TelaLivros(aluno, materia.getId());
                telaLivros.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Matéria não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma matéria.", "Erro", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnConsultarLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCursos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCursos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCursos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCursos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCursos_Materias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarLivros;
    private javax.swing.JButton btnConsultarMaterias;
    private javax.swing.JComboBox<String> comboboxMaterias;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtAulas;
    // End of variables declaration//GEN-END:variables
}
